--------------------------------------------------------
--  File created - Friday-February-05-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCE_EVENT_T
--------------------------------------------------------

  CREATE TABLE "SAKAIUSER"."ATTENDANCE_EVENT_T" 
   (	"A_EVENT_ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"START_DATE_TIME" TIMESTAMP (6), 
	"END_DATE_TIME" TIMESTAMP (6), 
	"IS_REOCCURRING" NUMBER(1,0), 
	"REOCCURRING_ID" NUMBER(19,0), 
	"IS_REQUIRED" NUMBER(1,0), 
	"RELEASED_TO" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"A_SITE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE_GRADE_T
--------------------------------------------------------

  CREATE TABLE "SAKAIUSER"."ATTENDANCE_GRADE_T" 
   (	"A_GRADE_ID" NUMBER(19,0), 
	"GRADE" FLOAT(126), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"A_SITE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE_RECORD_T
--------------------------------------------------------

  CREATE TABLE "SAKAIUSER"."ATTENDANCE_RECORD_T" 
   (	"A_RECORD_ID" NUMBER(19,0), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"A_EVENT_ID" NUMBER(19,0), 
	"RECORD_COMMENT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RECORD_COMMENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE_SITE_T
--------------------------------------------------------

  CREATE TABLE "SAKAIUSER"."ATTENDANCE_SITE_T" 
   (	"A_SITE_ID" NUMBER(19,0), 
	"SITE_ID" VARCHAR2(255 CHAR), 
	"DEFAULT_STATUS" VARCHAR2(255 CHAR), 
	"MAXIMUM_GRADE" FLOAT(126), 
	"IS_GRADE_SHOWN" NUMBER(1,0), 
	"SEND_TO_GRADEBOOK" NUMBER(1,0), 
	"GRADEBOOK_ITEM_NAME" VARCHAR2(255 CHAR), 
	"SHOW_COMMENTS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATTENDANCE_STATUS_T
--------------------------------------------------------

  CREATE TABLE "SAKAIUSER"."ATTENDANCE_STATUS_T" 
   (	"A_STATUS_ID" NUMBER(19,0), 
	"IS_ACTIVE" NUMBER(1,0), 
	"STATUS" VARCHAR2(255 CHAR), 
	"SORT_ORDER" NUMBER(10,0), 
	"A_SITE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00199065
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAKAIUSER"."SYS_C00199065" ON "SAKAIUSER"."ATTENDANCE_EVENT_T" ("A_EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00202815
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAKAIUSER"."SYS_C00202815" ON "SAKAIUSER"."ATTENDANCE_GRADE_T" ("A_GRADE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00199068
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAKAIUSER"."SYS_C00199068" ON "SAKAIUSER"."ATTENDANCE_RECORD_T" ("A_RECORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00199070
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAKAIUSER"."SYS_C00199070" ON "SAKAIUSER"."ATTENDANCE_SITE_T" ("A_SITE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00202818
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAKAIUSER"."SYS_C00202818" ON "SAKAIUSER"."ATTENDANCE_STATUS_T" ("A_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_EVENT_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_EVENT_T" ADD PRIMARY KEY ("A_EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_EVENT_T" MODIFY ("A_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_EVENT_T" MODIFY ("A_EVENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_GRADE_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_GRADE_T" ADD PRIMARY KEY ("A_GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_GRADE_T" MODIFY ("A_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_GRADE_T" MODIFY ("A_GRADE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_RECORD_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_RECORD_T" ADD PRIMARY KEY ("A_RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_RECORD_T" MODIFY ("A_EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_RECORD_T" MODIFY ("A_RECORD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_SITE_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_SITE_T" ADD PRIMARY KEY ("A_SITE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_SITE_T" MODIFY ("A_SITE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_STATUS_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_STATUS_T" ADD PRIMARY KEY ("A_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_STATUS_T" MODIFY ("A_SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "SAKAIUSER"."ATTENDANCE_STATUS_T" MODIFY ("A_STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE_EVENT_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_EVENT_T" ADD CONSTRAINT "FK65EC4C79E9210FFF" FOREIGN KEY ("A_SITE_ID")
	  REFERENCES "SAKAIUSER"."ATTENDANCE_SITE_T" ("A_SITE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE_GRADE_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_GRADE_T" ADD CONSTRAINT "FKC8A83E76E9210FFF" FOREIGN KEY ("A_SITE_ID")
	  REFERENCES "SAKAIUSER"."ATTENDANCE_SITE_T" ("A_SITE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE_RECORD_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_RECORD_T" ADD CONSTRAINT "FK1765B47C22917075" FOREIGN KEY ("A_EVENT_ID")
	  REFERENCES "SAKAIUSER"."ATTENDANCE_EVENT_T" ("A_EVENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE_STATUS_T
--------------------------------------------------------

  ALTER TABLE "SAKAIUSER"."ATTENDANCE_STATUS_T" ADD CONSTRAINT "FK95A2B3DDE9210FFF" FOREIGN KEY ("A_SITE_ID")
	  REFERENCES "SAKAIUSER"."ATTENDANCE_SITE_T" ("A_SITE_ID") ENABLE;
