ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN END_DATE_TIME;
ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN IS_REOCCURRING;
ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN REOCCURRING_ID;
ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN IS_REQUIRED;
ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN RELEASED_TO;
ALTER TABLE ATTENDANCE_EVENT_T DROP COLUMN LOCATION;

ALTER TABLE ATTENDANCE_GRADE_T MODIFY USER_ID VARCHAR2(99) NULL DEFAULT NULL;

DROP TABLE ATTENDANCE_ITEM_STATS_T;

ALTER TABLE ATTENDANCE_SITE_T MODIFY IS_GRADE_SHOWN NUMBER(1) NULL DEFAULT 0;
ALTER TABLE ATTENDANCE_SITE_T MODIFY SEND_TO_GRADEBOOK NUMBER(1,0) NULL DEFAULT 0;
ALTER TABLE ATTENDANCE_SITE_T MODIFY AUTO_GRADING NUMBER(1,0) NULL DEFAULT 0;
ALTER TABLE ATTENDANCE_SITE_T MODIFY GRADE_BY_SUBTRACTION NUMBER(1,0) NULL DEFAULT 1;
ALTER TABLE ATTENDANCE_SITE_T MODIFY SHOW_COMMENTS NUMBER(1,0) NULL DEFAULT 0;

ALTER TABLE ATTENDANCE_SITE_T DROP COLUMN SYNC;
ALTER TABLE ATTENDANCE_SITE_T DROP COLUMN SYNC_TIME;

ALTER TABLE ATTENDANCE_RULE_T MODIFY START_RANGE NUMBER(11, 0) NOT NULL DEFAULT '0';

ALTER TABLE ATTENDANCE_RULE_T MODIFY POINTS NUMBER(19,4) NOT NULL DEFAULT '0';

ALTER TABLE ATTENDANCE_STATUS_T MODIFY IS_ACTIVE NUMBER(1,0) NULL DEFAULT 1;

ALTER TABLE ATTENDANCE_STATUS_T MODIFY STATUS VARCHAR2(20) NULL DEFAULT NULL;

DROP TABLE ATTENDANCE_USER_STATS_T;