ALTER TABLE ATTENDANCE_EVENT_T
    DROP END_DATE_TIME,
    DROP IS_REOCCURRING,
    DROP REOCCURRING_ID,
    DROP IS_REQUIRED,
    DROP RELEASED_TO,
    DROP LOCATION;

ALTER TABLE ATTENDANCE_GRADE_T CHANGE USER_ID USER_ID VARCHAR(99) NULL DEFAULT NULL;

DROP TABLE ATTENDANCE_ITEM_STATS_T;

ALTER TABLE ATTENDANCE_SITE_T CHANGE IS_GRADE_SHOWN IS_GRADE_SHOWN BIT(1) NULL DEFAULT b'0', CHANGE SEND_TO_GRADEBOOK SEND_TO_GRADEBOOK BIT(1) NULL DEFAULT b'0', CHANGE AUTO_GRADING AUTO_GRADING BIT(1) NULL DEFAULT b'0', CHANGE GRADE_BY_SUBTRACTION GRADE_BY_SUBTRACTION BIT(1) NULL DEFAULT b'1', CHANGE SHOW_COMMENTS SHOW_COMMENTS BIT(1) NULL DEFAULT b'0';

ALTER TABLE ATTENDANCE_SITE_T
    DROP SYNC,
    DROP SYNC_TIME;

ALTER TABLE ATTENDANCE_RULE_T CHANGE START_RANGE START_RANGE INT(11) NOT NULL DEFAULT '0';

ALTER TABLE ATTENDANCE_RULE_T CHANGE POINTS POINTS DOUBLE NOT NULL DEFAULT '0';

ALTER TABLE ATTENDANCE_STATUS_T CHANGE IS_ACTIVE IS_ACTIVE BIT(1) NULL DEFAULT b'1';

ALTER TABLE ATTENDANCE_STATUS_T CHANGE STATUS STATUS VARCHAR(20) NULL DEFAULT NULL;

DROP TABLE ATTENDANCE_USER_STATS_T;